package com.jecrc.learning_edge
import android.content.Intent
import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import com.google.firebase.database.DataSnapshot
import com.google.firebase.database.DatabaseError
import com.google.firebase.database.DatabaseReference
import com.google.firebase.database.FirebaseDatabase
import com.google.firebase.database.ValueEventListener



class MainActivity : AppCompatActivity(), UserDataListener {

    private lateinit var databaseReference: DatabaseReference

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        databaseReference = FirebaseDatabase.getInstance().reference

        // Get the name, branch, and semester from the intent
        val name = intent.getStringExtra("name")
        val branch = intent.getStringExtra("branch")
        val semester = intent.getStringExtra("semester")

        // Save user data to the Firebase Realtime Database
        if (name != null) {
            if (branch != null) {
                if (semester != null) {
                    saveUserData(name, branch, semester)
                }
            }
        }

        // Initialize your fragments and set up the navigation as you have done before
    }

    override fun saveUserData(name: String, branch: String, semester: String) {
        // Save user data to the Firebase Realtime Database
        val userReference = databaseReference.child("Users").push()
        val userKey = userReference.key // Obtain the unique key generated by Firebase

        val userMap = hashMapOf(
            "name" to name,
            "branch" to branch,
            "semester" to semester
        )

        userKey?.let {
            userReference.setValue(userMap)
                .addOnCompleteListener { task ->
                    if (task.isSuccessful) {
                        // Data successfully saved
                        // You can do additional operations here if needed
                        Log.d("Firebase", "Data saved successfully")
                    } else {
                        // An error occurred while saving the data
                        Log.e("Firebase", "Data save error: ${task.exception}")
                    }
                }
        }
    }

    // Fetch the user's name from the Firebase Realtime Database
    // Attach a ValueEventListener to retrieve user data
    override fun getUserNameFromDatabase(callback: (String) -> Unit) {
        val userReference = databaseReference.child("users")

        // Attach a ValueEventListener to retrieve user data
        userReference.addListenerForSingleValueEvent(object : ValueEventListener {
            override fun onDataChange(snapshot: DataSnapshot) {
                // Assuming you have only one user entry in the database
                for (userSnapshot in snapshot.children) {
                    val name = userSnapshot.child("name").getValue(String::class.java)
                    callback(name ?: "Unknown")
                    return // Exit the loop after retrieving the user's name
                }
                // If no user found or error occurred, return "Unknown"
                callback("Unknown")
            }

            override fun onCancelled(error: DatabaseError) {
                Log.e("Firebase", "Error getting user data: ${error.message}")
                callback("Unknown")
            }
        })
    }

    // Rest of your code for MainActivity, navigation, and fragments...
}
